func: draft implementation of catalog repo visibility on creation
cycloidio/terraform-provider-cycloid pull request #25
Opened 2024-12-04 13:22 UTC by fhacloid

2025-01-15 13:24 UTC, xescugc commented on generator_config.yml
> +  config_repository:
?

2025-01-15 13:24 UTC, xescugc commented on generator_config.yml
> +      - data.created_at
Should this be `"` as you did for everything else

2025-01-15 13:24 UTC, xescugc commented on resource_catalog_repository/catalog_repository_resource.go
> +						// },
?

2025-01-15 13:24 UTC, xescugc commented on swagger_converter/converter.go
> +func (c Converter) Convert() error {
Go documentaiton has to start with the same name as the function, so `Convert`

2025-01-15 13:24 UTC, xescugc commented on swagger_converter/converter.go
> +func (c Converter) Fetch() error {
?

2025-01-15 13:24 UTC, xescugc commented on swagger_converter/utils/utils.go
> +func CurlToFile(url, filename string) error {
Is this generated or you wrote them?

2025-01-15 13:24 UTC, xescugc commented on tests/utils/utils.go
> +func WaitForBackend(timeoutInSec int) error {
Use Go formatting for commetns please, check on all the codebase to fix this, and comment all functions plz

2025-01-15 16:10 UTC, fhacloid commented on DEVELOPING_TIPS.md
> +- [`just`](https://just.systems/) -> for justfile, replaces make
That is not the subject of this PR, this file has been removed.

2025-01-15 16:13 UTC, fhacloid commented on DEVELOPING_TIPS.md
> +By default, tests will spin up the backend using the `./ci/dc.sh up_default` command, execute the tests, then exec `./ci/dc.sh clean`.
done.

2025-01-15 16:40 UTC, fhacloid commented on generator_config.yml
> +  config_repository:
I was keeping it around, in case I would need/fix the generation again.

You prefer I delete it ?

2025-01-15 16:57 UTC, fhacloid commented on swagger_converter/utils/utils.go
> +func CurlToFile(url, filename string) error {
I wrote them

2025-01-15 16:57 UTC, fhacloid commented on swagger_converter/converter.go
> +func (c Converter) Convert() error {
👌🏽

2025-01-15 16:58 UTC, fhacloid commented on DEVELOPING_TIPS.md
> +To start the tests use `go test -v ./... -count=1`.
There is now.

2025-01-17 10:51 UTC, xescugc requested changes

2025-01-17 10:51 UTC, xescugc commented on Makefile
> +	@tfplugingen-framework generate data-sources --input ./out_code_spec.json --output .
Do we have any?

2025-01-17 10:51 UTC, xescugc commented on docs/index.md
> ----
Why remove this?

2025-01-17 10:51 UTC, xescugc commented on DEVELOPING_TIPS.md
> +To initialize the backend, you can use the `./ci/init_backend.sh` script, see examples below.
Document the `make` alternative

2025-01-17 10:51 UTC, xescugc commented on DEVELOPING_TIPS.md
> +You can use helper commands in `make` or `just`:
Which are?

2025-01-17 10:51 UTC, xescugc commented on DEVELOPING_TIPS.md
> +By default, tests using `go test` will spin up the backend using the `./ci/dc.sh up_default` command, execute the tests, then exec `./ci/dc.sh clean`.
`make`

2025-01-17 16:02 UTC, fhacloid commented on Makefile
> +	@tfplugingen-framework generate data-sources --input ./out_code_spec.json --output .
Yes https://github.com/cycloidio/terraform-provider-cycloid/pull/25/files#diff-4acd108c9d6490a6b984a6517926b3e85502480b661957e003878c3c975a0dd1

2025-01-17 16:06 UTC, fhacloid commented on DEVELOPING_TIPS.md
> +To initialize the backend, you can use the `./ci/init_backend.sh` script, see examples below.
I had been done already: https://github.com/cycloidio/terraform-provider-cycloid/blob/5a69e1da2ccbabf3b97db0d34c931ab51553b0e4/DEVELOPING_TIPS.md?plain=1#L59

2025-01-17 16:06 UTC, fhacloid commented on DEVELOPING_TIPS.md
> +You can use helper commands in `make` or `just`:
look line 63

2025-01-17 16:07 UTC, fhacloid commented on docs/index.md
> ----
Was deleted by mistake, just added it.

2025-01-24 10:00 UTC, xescugc requested changes
Check the comments.

Is there a documentation on how to add a new Swagger exception (those changes that we need to do to the spect in order to correctly work).

2025-01-24 10:11 UTC, fhacloid commented on compose.yml
> +# This is just to ensure docker compose will error if secrets are not provider.
I really don't like this pattern of having to clone/update the whole backend repo for my local tests to work.

It's not a lot of work to update the local config of the tf provider local backend to work in case of a backend config change.

2025-01-24 10:11 UTC, fhacloid commented on ci/init-backend.sh
> +#! /usr/bin/env sh
It could, but still require to clone the backend repo to add a command. I like to keep things separate.

The tf provider doesn't need alot of provisioning to get a minimal backend working.

2025-01-24 10:47 UTC, fhacloid commented on compose.yml
> +# This is just to ensure docker compose will error if secrets are not provider.
Removed it, to implement in a different PR.

2025-01-24 10:48 UTC, fhacloid commented on ci/init-backend.sh
> +#! /usr/bin/env sh
Removed it, to implement on a different PR.

2025-01-24 11:07 UTC, fhacloid commented
@xescugc Updated the PR:
- Removed tests, docker compose dev env and out of scope stuff
- Added docs on the swagger converter and codegen.

2025-01-24 11:26 UTC, xescugc approved these changes

2025-01-24 12:01 UTC, merged